// Package checks implements the contract-level projection checks of
// verification-ladder rung 1 (spec §12.6, §6.2): repository naming rules,
// recorded exceptions, file-size review signals, and generated-file
// ownership. The check command runs them inside the "contract" gate.
package checks

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/Choaterboater/pika/internal/discover"
	"github.com/Choaterboater/pika/internal/profiles"
)

// SeverityError marks violations that fail the gate; every other severity
// (M1 uses "warning") is a review signal that check reports without
// failing.
const SeverityError = "error"

// Rule scopes recognized by Naming (the data lives in the profile packs).
const (
	scopePathSegments = "path-segments"
	scopeFileLines    = "file-lines"
	scopeGenPatterns  = "generated-patterns"
)

// defaultKebabCase is the brief's default path pattern, applied when a
// path-segments rule carries no profile pattern override. `-` is last in
// the character class deliberately: `[a-z0-9.-_]` (dash between `.` and
// `_`) is not three literals, it is the byte range 0x2E-0x5F — which
// swallows every uppercase letter and `/:;<=>?@[\]^` while excluding `-`
// itself, so it silently accepted camelCase and rejected an actual
// kebab-case name. core@1's own explicit pattern already orders `-`
// last for the same reason; this fallback now matches it exactly.
const defaultKebabCase = `^[a-z0-9][a-z0-9._-]*$`

// generatedHeaderRe matches a generator declaration such as Go's
// "// Code generated by protoc-gen-go. DO NOT EDIT." (spec §6.2: generated
// files declare their generator).
var generatedHeaderRe = regexp.MustCompile(`(?i)code generated.*do not edit`)

// headerScanLines bounds how deep into a file the generator-declaration
// scan looks.
const headerScanLines = 5

// Violation is one finding: a rule, its severity, the repository path it
// fired on, and a human-readable message.
type Violation struct {
	RuleID   string `json:"ruleId"`
	Severity string `json:"severity"`
	Path     string `json:"path"`
	Message  string `json:"message"`
}

// compiledRule carries per-rule precomputation so the file walk does no
// parsing per rule per path.
type compiledRule struct {
	rule      profiles.NamingRule
	re        *regexp.Regexp // path-segments pattern (set only when valid)
	threshold int            // file-lines cutoff
	hasLimit  bool           // false when the threshold data is unusable
	globs     []string       // generated-patterns globs
}

// Naming walks repoRoot and evaluates the resolved naming rules against
// every repository file. exceptions suppresses findings: an exception
// whose path equals the finding's path (or an ancestor directory of it)
// and whose rule ID matches the firing rule marks the path accepted. The
// repository root itself is a legal package root and is never a finding;
// dot-prefixed path segments (VCS internals, .project state) are skipped.
// The returned slice is ordered by walk order, then rule order.
func Naming(repoRoot string, rules []profiles.NamingRule, exceptions map[string][]Exception) []Violation {
	compiled := make([]compiledRule, 0, len(rules))
	for _, r := range rules {
		compiled = append(compiled, compileRule(r))
	}
	var out []Violation
	for _, rel := range walkFiles(repoRoot) {
		for _, cr := range compiled {
			for _, v := range cr.violations(repoRoot, rel) {
				if excepted(exceptions, v.RuleID, rel) {
					continue
				}
				out = append(out, v)
			}
		}
	}
	return out
}

// compileRule precomputes matcher data. Pack data is embedded and
// reviewed, so malformed matcher data leaves the rule inert rather than
// inventing a failure Naming cannot report (its signature carries no
// error); a warning-only rule going quiet is the safe direction.
func compileRule(r profiles.NamingRule) compiledRule {
	cr := compiledRule{rule: r}
	switch r.Scope {
	case scopePathSegments:
		pat := r.Pattern
		if pat == "" {
			pat = defaultKebabCase
		}
		if re, err := regexp.Compile(pat); err == nil {
			cr.re = re
		}
	case scopeFileLines:
		if n, err := strconv.Atoi(strings.TrimSpace(r.Pattern)); err == nil {
			cr.threshold, cr.hasLimit = n, true
		}
	case scopeGenPatterns:
		for _, g := range strings.Split(r.Pattern, ",") {
			if g = strings.TrimSpace(g); g != "" {
				cr.globs = append(cr.globs, g)
			}
		}
	}
	return cr
}

// violations evaluates one compiled rule against one repository file and
// returns at most one violation per (file, rule).
func (cr compiledRule) violations(repoRoot, rel string) []Violation {
	switch cr.rule.Scope {
	case scopePathSegments:
		return cr.pathSegmentViolation(rel)
	case scopeFileLines:
		if !cr.hasLimit {
			return nil
		}
		n, err := countLines(filepath.Join(repoRoot, filepath.FromSlash(rel)))
		if err != nil || n <= cr.threshold {
			return nil
		}
		return []Violation{{
			RuleID:   cr.rule.RuleID,
			Severity: cr.rule.Severity,
			Path:     rel,
			Message:  fmt.Sprintf("file has %d lines, exceeding the %d-line review threshold", n, cr.threshold),
		}}
	case scopeGenPatterns:
		matched := false
		for _, g := range cr.globs {
			if ok, err := path.Match(g, rel); err == nil && ok {
				matched = true
				break
			}
		}
		if !matched {
			return nil
		}
		if declaresGenerator(filepath.Join(repoRoot, filepath.FromSlash(rel))) {
			return nil
		}
		return []Violation{{
			RuleID:   cr.rule.RuleID,
			Severity: cr.rule.Severity,
			Path:     rel,
			Message:  "generated file is missing its generator declaration header",
		}}
	}
	return nil
}

// pathSegmentViolation applies a path-segments rule to a file's path
// segments. A file's final segment is compared by its stem (name without
// extension), so ecosystem-mandated extensions never look like style
// violations. A rule with banned names fires on a banned segment; a rule
// with a pattern fires on segments that do not match it.
func (cr compiledRule) pathSegmentViolation(rel string) []Violation {
	segs := strings.Split(rel, "/")
	names := slices.Clone(segs)
	names[len(names)-1] = stem(segs[len(segs)-1])

	if len(cr.rule.Banned) > 0 {
		var banned []string
		for _, nm := range names {
			if slices.Contains(cr.rule.Banned, nm) {
				banned = append(banned, nm)
			}
		}
		if len(banned) == 0 {
			return nil
		}
		return []Violation{{
			RuleID:   cr.rule.RuleID,
			Severity: cr.rule.Severity,
			Path:     rel,
			Message: fmt.Sprintf("catch-all name %s requires a recorded exception or a narrower name",
				quoteJoin(banned)),
		}}
	}
	if cr.re == nil {
		return nil
	}
	var bad []string
	for _, nm := range names {
		// Stem exemptions (e.g. README, Makefile) are names the
		// ecosystem has made conventional; they are never style
		// violations of a pattern rule.
		if slices.Contains(cr.rule.Exempt, nm) {
			continue
		}
		if !cr.re.MatchString(nm) {
			bad = append(bad, nm)
		}
	}
	if len(bad) == 0 {
		return nil
	}
	return []Violation{{
		RuleID:   cr.rule.RuleID,
		Severity: cr.rule.Severity,
		Path:     rel,
		Message: fmt.Sprintf("path segment %s does not match the kebab-case naming rule",
			quoteJoin(bad)),
	}}
}

// stem strips a single trailing extension. Multi-dot suffixes (".d.ts")
// keep their stem dotted and are reported as-is rather than guessed at.
func stem(name string) string {
	if i := strings.LastIndex(name, "."); i > 0 {
		return name[:i]
	}
	return name
}

// excepted reports whether an exception with the given rule ID covers rel,
// either directly or through an ancestor-directory exception.
func excepted(exceptions map[string][]Exception, ruleID, rel string) bool {
	for p := rel; ; p = path.Dir(p) {
		for _, ex := range exceptions[p] {
			if ex.RuleID == ruleID {
				return true
			}
		}
		if p == "." {
			return false
		}
	}
}

// walkFiles returns the slash-separated repository-relative paths of
// every regular file naming should judge, in lexical order.
//
// A real, already-built repository routinely carries gitignored build
// output and runtime data — a `dist/`, a `build/`, a data directory, a
// `__pycache__` (which does not start with a dot and is not one of
// discover.SkipDirs's fixed names) — that can dwarf the repository's own
// source by orders of magnitude and was never authored by anyone this
// rule could hold accountable. When repoRoot is a git work tree,
// gitTrackedFiles asks git directly rather than guessing at names: git
// already knows every ignore rule in play, at every directory depth,
// and its answer never descends into an ignored directory to begin
// with. Only when git cannot answer (not a git repository, or the git
// binary is unavailable) does the walk fall back to the name-based
// exclusion below.
func walkFiles(repoRoot string) []string {
	if files, ok := gitTrackedFiles(repoRoot); ok {
		return files
	}
	return filesystemWalkFiles(repoRoot)
}

// gitTrackedFiles lists every path git considers part of the repository:
// committed, staged, or untracked-but-not-ignored. ok is false when
// repoRoot is not a git work tree or git is not on PATH, in which case
// the caller must fall back rather than treat an empty answer as "no
// files" — an environmental failure here must never silently narrow
// what naming checks.
func gitTrackedFiles(repoRoot string) (files []string, ok bool) {
	if _, err := exec.LookPath("git"); err != nil {
		return nil, false
	}
	if out, err := gitOutput(repoRoot, "rev-parse", "--is-inside-work-tree"); err != nil || strings.TrimSpace(out) != "true" {
		return nil, false
	}
	out, err := gitOutput(repoRoot, "ls-files", "--cached", "--others", "--exclude-standard", "-z")
	if err != nil {
		return nil, false
	}
	for _, p := range strings.Split(out, "\x00") {
		if p == "" {
			continue
		}
		rel := filepath.ToSlash(p)
		if hasDotSegment(rel) {
			continue
		}
		// git lists what the index and the working tree agree exists;
		// a path removed from disk without `git rm` is still tracked
		// and would otherwise be reported unreadable rather than
		// simply absent.
		if info, err := os.Lstat(filepath.Join(repoRoot, filepath.FromSlash(rel))); err != nil || info.IsDir() {
			continue
		}
		files = append(files, rel)
	}
	slices.Sort(files)
	return files, true
}

// gitOutput runs one git subcommand in dir and returns its stdout.
func gitOutput(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	return string(out), err
}

// filesystemWalkFiles is walkFiles's fallback for a repository git
// cannot answer for: the root itself, any dot-prefixed path segment
// (.git, .project, .github, dotfiles), and any directory
// discover.SkipDirs names (node_modules, target, DerivedData —
// vendored dependencies and build/IDE output, not the repository's own
// naming to judge) are excluded; unreadable entries are skipped rather
// than fatal.
func filesystemWalkFiles(repoRoot string) []string {
	var files []string
	err := filepath.WalkDir(repoRoot, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil //nolint:nilerr // unreadable entries are skipped, not fatal
		}
		rel, rerr := filepath.Rel(repoRoot, p)
		if rerr != nil {
			return nil //nolint:nilerr
		}
		rel = filepath.ToSlash(rel)
		if rel == "." {
			return nil // the repository root is a legal package root
		}
		if hasDotSegment(rel) {
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			if discover.SkipDirs[d.Name()] {
				return fs.SkipDir
			}
			return nil
		}
		files = append(files, rel)
		return nil
	})
	if err != nil {
		// WalkDir on a readable root does not fail; a failed root walk
		// yields no files and therefore no findings.
		return nil
	}
	return files
}

func hasDotSegment(rel string) bool {
	for _, seg := range strings.Split(rel, "/") {
		if strings.HasPrefix(seg, ".") {
			return true
		}
	}
	return false
}

// countLines counts lines the way wc -l does: newline characters, plus a
// non-empty trailing line without a final newline.
func countLines(p string) (int, error) {
	f, err := os.Open(p)
	if err != nil {
		return 0, err
	}
	defer f.Close()

	buf := make([]byte, 64*1024)
	lines, last := 0, byte('\n')
	for {
		n, rerr := f.Read(buf)
		if n > 0 {
			lines += bytes.Count(buf[:n], []byte{'\n'})
			last = buf[n-1]
		}
		if rerr == io.EOF {
			break
		}
		if rerr != nil {
			return lines, rerr
		}
	}
	if last != '\n' {
		lines++
	}
	return lines, nil
}

// declaresGenerator scans the first headerScanLines lines of p for a
// generator declaration.
func declaresGenerator(p string) bool {
	f, err := os.Open(p)
	if err != nil {
		return false
	}
	defer f.Close()

	sc := bufio.NewScanner(io.LimitReader(f, 4*1024))
	for i := 0; i < headerScanLines && sc.Scan(); i++ {
		if generatedHeaderRe.MatchString(sc.Text()) {
			return true
		}
	}
	return false
}

func quoteJoin(vs []string) string {
	quoted := make([]string, len(vs))
	for i, v := range vs {
		quoted[i] = strconv.Quote(v)
	}
	return strings.Join(quoted, ", ")
}
