package checks

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// A real exceptions.yaml carries a header comment, a redundant `path:`
// field repeating the mapping key, single-quoted multi-line reasons
// with escaped quotes, and — since a path can violate two rules at
// once — a list-shaped value for one path. The rewrite must touch only
// the "owner:" scalar it is asked to change and leave every other byte
// exactly as it was: a re-marshal would drop the comment, drop the
// redundant path field, and reflow every quoted scalar, turning a
// one-field ownership change into an unreviewable diff of a file
// nobody meant to touch.
const mixedExceptionsFixture = `# Recorded naming-rule exceptions (spec §5.3).
# Generated by ` + "`pika adopt`" + `; each decision reviewed and written by hand.

src/utils/helpers.go:
  rule-id: naming-catch-all
  path: src/utils/helpers.go
  reason: 'inherited at adoption; predates this contract''s naming rules.'
  owner: pika adopt
  review-condition: 'reopen at the next refactor of this package.'
src/Common/tools.go:
  - rule-id: naming-catch-all
    path: src/Common/tools.go
    reason: 'catch-all directory, inherited.'
    owner: pika adopt
    review-condition: 'reopen when Common/ is split by responsibility.'
  - rule-id: naming-kebab-case
    path: src/Common/tools.go
    reason: 'mixed-case directory, inherited.'
    owner: pika adopt
    review-condition: 'reopen when Common/ is renamed.'
vendor/legacy/README:
  rule-id: naming-kebab-case
  reason: 'a human already accepted this one.'
  owner: '@alice (team lead)'
  review-condition: 'reopen if vendor/legacy is ever updated.'
`

func TestReassignAutoRecordedOwnersRewritesOnlyPlaceholderOwners(t *testing.T) {
	root := t.TempDir()
	writeTree(t, root, map[string]string{ExceptionsFile: mixedExceptionsFixture})

	got, err := ReassignAutoRecordedOwners(root, "@bob (new maintainer)")
	if err != nil {
		t.Fatalf("ReassignAutoRecordedOwners: %v", err)
	}
	if got.Reassigned != 3 {
		t.Fatalf("Reassigned = %d, want 3 (one for helpers.go, two for the list-shaped tools.go)", got.Reassigned)
	}
	if got.Owner != "@bob (new maintainer)" {
		t.Errorf("Owner = %q", got.Owner)
	}
	wantRecords := map[string]bool{
		"src/utils/helpers.go naming-catch-all": true,
		"src/Common/tools.go naming-catch-all":  true,
		"src/Common/tools.go naming-kebab-case": true,
	}
	for _, r := range got.Records {
		key := r.Path + " " + r.RuleID
		if !wantRecords[key] {
			t.Errorf("unexpected reassigned record: %+v", r)
		}
		delete(wantRecords, key)
	}
	if len(wantRecords) != 0 {
		t.Errorf("missing reassigned records: %v", wantRecords)
	}

	after, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(ExceptionsFile)))
	if err != nil {
		t.Fatal(err)
	}
	text := string(after)

	// Untouched: comment header, redundant path fields, quoting, the
	// human-owned record, every reason and review-condition verbatim.
	for _, want := range []string{
		"# Recorded naming-rule exceptions (spec §5.3).",
		"# Generated by `pika adopt`; each decision reviewed and written by hand.",
		"path: src/utils/helpers.go",
		"path: src/Common/tools.go",
		"reason: 'inherited at adoption; predates this contract''s naming rules.'",
		"reason: 'catch-all directory, inherited.'",
		"reason: 'mixed-case directory, inherited.'",
		"owner: '@alice (team lead)'",
		"reason: 'a human already accepted this one.'",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("rewrite lost or reflowed: %q\ngot:\n%s", want, text)
		}
	}
	if strings.Contains(text, "owner: pika adopt") {
		t.Errorf("a placeholder owner survived the reassignment:\n%s", text)
	}
	if n := strings.Count(text, `owner: "@bob (new maintainer)"`); n != 3 {
		t.Errorf("new owner appears %d times, want 3:\n%s", n, text)
	}

	// The result still loads, and gate 1's own loader agrees nothing is
	// left owned by the placeholder.
	loaded, err := LoadExceptions(root)
	if err != nil {
		t.Fatalf("rewritten file failed to load: %v", err)
	}
	for _, list := range loaded {
		for _, ex := range list {
			if ex.Owner == AutoRecordedOwner {
				t.Errorf("loaded record %s/%s still owned by the placeholder", ex.Path, ex.RuleID)
			}
		}
	}
}

func TestReassignIsIdempotentOnASecondRun(t *testing.T) {
	root := t.TempDir()
	writeTree(t, root, map[string]string{ExceptionsFile: mixedExceptionsFixture})
	if _, err := ReassignAutoRecordedOwners(root, "@bob"); err != nil {
		t.Fatal(err)
	}
	second, err := ReassignAutoRecordedOwners(root, "@bob")
	if err != nil {
		t.Fatal(err)
	}
	if second.Reassigned != 0 {
		t.Errorf("second run reassigned %d records, want 0: nothing is owned by the placeholder anymore", second.Reassigned)
	}
}

func TestReassignRefusesAnEmptyOwner(t *testing.T) {
	root := t.TempDir()
	writeTree(t, root, map[string]string{ExceptionsFile: mixedExceptionsFixture})
	if _, err := ReassignAutoRecordedOwners(root, "   "); err == nil {
		t.Fatal("ReassignAutoRecordedOwners(\"   \") = nil error, want a refusal")
	}
}

func TestReassignRefusesThePlaceholderAsTheNewOwner(t *testing.T) {
	root := t.TempDir()
	writeTree(t, root, map[string]string{ExceptionsFile: mixedExceptionsFixture})
	if _, err := ReassignAutoRecordedOwners(root, AutoRecordedOwner); err == nil {
		t.Fatal("reassigning to the placeholder itself must be refused: it is not a reassignment")
	}
}

func TestReassignWithNoExceptionsFileIsANoOp(t *testing.T) {
	root := t.TempDir()
	got, err := ReassignAutoRecordedOwners(root, "@bob")
	if err != nil {
		t.Fatalf("ReassignAutoRecordedOwners on a repository with no exceptions record: %v", err)
	}
	if got.Reassigned != 0 {
		t.Errorf("Reassigned = %d, want 0", got.Reassigned)
	}
}

func TestReassignRefusesAnUnloadableFile(t *testing.T) {
	root := t.TempDir()
	writeTree(t, root, map[string]string{
		ExceptionsFile: "src/x:\n  rule-id: naming-catch-all\n  owner: pika adopt\n", // missing reason, review-condition
	})
	if _, err := ReassignAutoRecordedOwners(root, "@bob"); err == nil {
		t.Fatal("an exceptions record that does not load must refuse rather than be rewritten")
	}
	after, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(ExceptionsFile)))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(after), "owner: pika adopt") {
		t.Error("the refused file was modified anyway")
	}
}
