package skills

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/Choaterboater/pika/internal/contract"
	"github.com/Choaterboater/pika/internal/profiles"
	"github.com/Choaterboater/pika/internal/repopath"
)

// The markers delimiting the kernel-owned region of a projection file.
// They are HTML comments so the region is invisible when the file is
// rendered and legible when it is read as text, and they are literal
// rather than templated so a file can be searched for them.
const (
	beginMarker = "<!-- pika:skills:begin -->"
	endMarker   = "<!-- pika:skills:end -->"
)

// generatedNotice is the first line inside every region. It exists for
// the human or agent who opens the file with no idea why it looks
// generated.
const generatedNotice = "<!-- Generated by `pika skills install`. Everything between these markers is kernel-owned: edit the source, not this copy. -->"

// The kinds of input a projection is generated from.
const (
	// SourceSkill is a canonical skill file in this repository.
	SourceSkill = "skill"
	// SourceGuidance is one profile pack's agent-guidance.
	SourceGuidance = "guidance"
)

// Source is one input a projection was generated from, with the digest
// of that input at generation time. Spec §9.2 requires a projection to
// identify its source and digest; this is that identification, and it is
// what makes a stale copy distinguishable from a current one.
type Source struct {
	Kind   string `json:"kind"`
	Ref    string `json:"ref"`
	Digest string `json:"digest"`
}

// sourceLine matches one provenance line inside a region.
var sourceLine = regexp.MustCompile(`^<!-- pika:source (skill|guidance) (\S+) (sha256:[0-9a-f]{64}) -->$`)

// body is everything a projection renders from: the canonical skills in
// the repository, and the agent guidance the resolved profile packs
// contribute. Both are inputs with digests, so both appear in the
// provenance header — a projection that changed because go@1's guidance
// changed says so, instead of reporting only that something moved.
//
// The provenance and the rendered region are computed once, at
// construction: every declared projection renders the same bytes, and a
// repository with several of them would otherwise hash and format the
// same inputs once per target.
type body struct {
	skills   []canonical
	guidance []profiles.GuidanceSet
	src      []Source
	region   []byte
	digest   string
}

func newBody(skills []canonical, guidance []profiles.GuidanceSet) body {
	b := body{skills: skills, guidance: guidance}
	b.src = b.provenance()
	core := b.renderCore()
	b.digest = digestOf(core)
	b.region = withRegionDigest(core, b.digest)
	return b
}

// sources lists the provenance of the rendered region: skills first in
// name order, then guidance in profile-composition order.
func (b body) sources() []Source { return b.src }

// provenance computes that list.
//
// A pack's digest here covers its guidance lines alone, not the whole
// pack. A pack edit that does not touch guidance cannot change what a
// projection says, so it must not be reported as having drifted it;
// profiles.lock is where whole-pack drift is already caught.
func (b body) provenance() []Source {
	out := make([]Source, 0, len(b.skills)+len(b.guidance))
	for _, s := range b.skills {
		out = append(out, Source{Kind: SourceSkill, Ref: s.rel, Digest: s.digest})
	}
	for _, g := range b.guidance {
		out = append(out, Source{Kind: SourceGuidance, Ref: g.Ref, Digest: digestOf([]byte(strings.Join(g.Lines, "\n")))})
	}
	return out
}

// renderCore builds the kernel-owned region without its own digest
// line: the markers, the provenance header, every canonical skill
// demoted one heading level so it nests under the host document, and
// the stack guidance the profile packs contribute.
//
// These are the exact bytes the region digest covers. Rendering them
// separately is what makes the scheme stable: the digest is a function
// of everything except the line that carries it, so regenerating an
// unchanged projection reproduces the same digest and therefore the
// same file.
func (b body) renderCore() []byte {
	var out bytes.Buffer
	out.WriteString(regionHead)
	for _, s := range b.src {
		fmt.Fprintf(&out, "<!-- pika:source %s %s %s -->\n", s.Kind, s.Ref, s.Digest)
	}
	for _, s := range b.skills {
		out.WriteString("\n")
		out.Write(demote(stripFrontmatter(s.body)))
	}
	if len(b.guidance) > 0 {
		out.WriteString("\n## Stack guidance\n\n")
		out.WriteString("From the profile packs this repository selects (")
		for i, g := range b.guidance {
			if i > 0 {
				out.WriteString(", ")
			}
			out.WriteString(g.Ref)
		}
		out.WriteString("):\n\n")
		for _, g := range b.guidance {
			for _, line := range g.Lines {
				fmt.Fprintf(&out, "- %s\n", collapse(line))
			}
		}
	}
	out.WriteString(endMarker + "\n")
	return out.Bytes()
}

// stripFrontmatter removes a leading YAML frontmatter block. The
// frontmatter tells a skill loader when to load a skill; a projection is
// always loaded, so carrying it across would state a condition nothing
// evaluates.
func stripFrontmatter(src []byte) []byte {
	if !bytes.HasPrefix(src, []byte("---\n")) {
		return src
	}
	rest := src[len("---\n"):]
	end := bytes.Index(rest, []byte("\n---\n"))
	if end < 0 {
		return src
	}
	return bytes.TrimLeft(rest[end+len("\n---\n"):], "\n")
}

// demote adds one level to every ATX heading so a skill's own `#` title
// nests beneath the host document's. A heading already at level six is
// left alone: seven hashes is not a heading, and silently emitting one
// would turn a demotion into a deletion.
func demote(src []byte) []byte {
	lines := bytes.Split(src, []byte("\n"))
	for i, line := range lines {
		hashes := 0
		for hashes < len(line) && line[hashes] == '#' {
			hashes++
		}
		if hashes == 0 || hashes >= 6 || hashes >= len(line) || line[hashes] != ' ' {
			continue
		}
		lines[i] = append([]byte("#"), line...)
	}
	return bytes.Join(lines, []byte("\n"))
}

// collapse folds a guidance line onto one line. Pack YAML folds long
// prose across source lines for readability; a Markdown bullet that
// carries those newlines through would end the list item at the first one.
func collapse(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// inspectProjection reports one declared projection against what the
// file on disk holds, without writing anything.
//
// The order of the two verdicts is deliberate. A region is checked
// against its OWN recorded digest before it is compared to anything its
// sources render to, because those two failures have opposite remedies:
// regenerating a stale copy costs nothing, and regenerating a tampered
// one destroys whatever somebody typed there. Asking "was this region
// edited?" first answers that question from the file alone, so a hand
// edit stays visible even when a source moved in the same working tree.
func inspectProjection(root *repopath.Root, p contract.Projection, b body) ProjectionStatus {
	st := ProjectionStatus{Harness: p.Harness, Path: p.Path, Sources: b.sources(), Region: b.digest}
	target := filepath.Join(root.Dir(), filepath.FromSlash(p.Path))
	doc, err := os.ReadFile(target)
	if errors.Is(err, fs.ErrNotExist) {
		st.State = StateAbsent
		st.Detail = "does not exist; write it with `pika skills install`"
		return st
	}
	if err != nil {
		st.State = StateUnreadable
		st.Detail = fmt.Sprintf("cannot be read: %v", err)
		return st
	}
	region, ok, err := extractRegion(doc)
	if err != nil {
		st.State = StateUnreadable
		st.Detail = err.Error()
		return st
	}
	if !ok {
		st.State = StateAbsent
		st.Detail = "carries no pika skills region; write it with `pika skills install`"
		return st
	}
	if err := verifyRegion(region); err != nil {
		st.State = StateTampered
		st.Detail = tamperedDetail(err)
		return st
	}
	if bytes.Equal(region, b.region) {
		st.State = StateCurrent
		return st
	}
	st.State = StateStale
	st.Detail = staleDetail(region, b)
	return st
}

// staleDetail explains why an intact region no longer matches its
// sources, naming the source that moved when one did. That is what the
// provenance header is for: without it every stale copy reads the same,
// and an operator is told only that something moved.
//
// Reaching here means the region still hashes to the digest it carries,
// so nothing anyone typed is at risk and `pika skills install` is safe.
func staleDetail(region []byte, b body) string {
	cited := parseSources(region)
	had := map[string]Source{}
	var order []string
	for _, s := range cited {
		had[s.Ref] = s
		order = append(order, s.Ref)
	}
	var moved []string
	for _, want := range b.sources() {
		got, ok := had[want.Ref]
		if !ok {
			moved = append(moved, fmt.Sprintf("was generated before %s %s existed", want.Kind, want.Ref))
			continue
		}
		if got.Digest != want.Digest {
			moved = append(moved, fmt.Sprintf("cites %s %s at %s, which is now %s", got.Kind, got.Ref, got.Digest, want.Digest))
		}
	}
	current := map[string]bool{}
	for _, want := range b.sources() {
		current[want.Ref] = true
	}
	for _, ref := range order {
		if !current[ref] {
			moved = append(moved, fmt.Sprintf("cites %s %s, which this repository no longer has", had[ref].Kind, ref))
		}
	}
	if len(moved) == 0 {
		// Every source this region cites is where it was, and the
		// region still hashes to its own digest, so nobody edited
		// either side: this pika renders the same inputs differently
		// from the one that wrote the file. Saying "a source moved"
		// here would name a file that did not change.
		return "cites every source at its current digest but no longer matches what this version of pika renders from them; regenerate it with `pika skills install`"
	}
	return strings.Join(moved, " and ") + "; regenerate it with `pika skills install`"
}

// parseSources reads the provenance lines out of a region.
func parseSources(region []byte) []Source {
	var out []Source
	for _, line := range strings.Split(string(region), "\n") {
		m := sourceLine.FindStringSubmatch(strings.TrimRight(line, "\r"))
		if m == nil {
			continue
		}
		out = append(out, Source{Kind: m[1], Ref: m[2], Digest: m[3]})
	}
	return out
}

// writeProjection regenerates one projection in place and reports the
// result. A file whose markers do not pair up is refused rather than
// rewritten: the kernel owns the region, not the file, and it cannot
// tell where the region ends.
//
// An install is allowed to overwrite a hand-edited region — that region
// is kernel property and this is the command that asserts it — but it
// says when it did. An operator whose edit is gone learns it here
// rather than from a diff a week later.
func writeProjection(root *repopath.Root, p contract.Projection, b body) (ProjectionStatus, error) {
	st := ProjectionStatus{Harness: p.Harness, Path: p.Path, Sources: b.sources(), Region: b.digest}
	target := filepath.Join(root.Dir(), filepath.FromSlash(p.Path))
	doc, err := os.ReadFile(target)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		st.State = StateUnreadable
		st.Detail = fmt.Sprintf("cannot be read: %v", err)
		return st, nil
	}
	next, err := splice(doc, b.region)
	if err != nil {
		st.State = StateUnreadable
		st.Detail = err.Error()
		return st, nil
	}
	if !bytes.Equal(doc, next) {
		if err := writeFile(target, next); err != nil {
			return st, err
		}
		st.Written = true
		if region, ok, err := extractRegion(doc); err == nil && ok {
			if bad := verifyRegion(region); bad != nil && !errors.Is(bad, errUnverifiable) {
				st.Detail = "replaced a hand-edited kernel-owned region: it " + bad.Error() +
					"; whatever was typed there is gone — recover it from version control and put it in the canonical skill instead"
			}
		}
	}
	st.State = StateCurrent
	return st, nil
}

// extractRegion returns the managed region of doc, markers included.
func extractRegion(doc []byte) ([]byte, bool, error) {
	start, end, err := regionBounds(doc)
	if err != nil || start < 0 {
		return nil, false, err
	}
	return doc[start:end], true, nil
}

// regionBounds locates the managed region: start is the index of the
// begin marker's line, end the index just past the newline that closes
// the end marker. start is -1 when there is no region. A second begin
// marker, or an end marker that never arrives, is an error — both are
// states where replacing "the" region would silently destroy text.
func regionBounds(doc []byte) (start, end int, err error) {
	begins := markerLines(doc, beginMarker)
	ends := markerLines(doc, endMarker)
	if len(begins) == 0 {
		if len(ends) > 0 {
			return -1, 0, fmt.Errorf("carries a %s with no matching %s; the kernel cannot tell where its region begins", endMarker, beginMarker)
		}
		return -1, 0, nil
	}
	if len(begins) > 1 {
		return -1, 0, fmt.Errorf("carries more than one %s; the kernel cannot tell which region is its own", beginMarker)
	}
	start = begins[0]
	for _, e := range ends {
		if e <= start {
			continue
		}
		end = e + len(endMarker)
		if end < len(doc) && doc[end] == '\n' {
			end++
		}
		return start, end, nil
	}
	return -1, 0, fmt.Errorf("carries a %s with no matching %s; the kernel cannot tell where its region ends", beginMarker, endMarker)
}

// markerLines returns the offset of every line in doc whose entire
// content is marker.
//
// A marker is a whole line, not a substring. Prose that names one —
// documentation explaining what the region is, which is the first thing
// anyone writes above it — mentions it inside an inline code span, and a
// substring search counts that as a second region and refuses to touch
// the file. Anchoring to the line makes the documentation and the
// mechanism able to coexist, which they have to: a marker nobody may
// write down is a marker nobody can explain.
func markerLines(doc []byte, marker string) []int {
	var out []int
	for offset := 0; offset < len(doc); {
		width := bytes.IndexByte(doc[offset:], '\n')
		line := doc[offset:]
		next := len(doc)
		if width >= 0 {
			line = doc[offset : offset+width]
			next = offset + width + 1
		}
		if string(bytes.TrimRight(line, "\r")) == marker {
			out = append(out, offset)
		}
		offset = next
	}
	return out
}

// splice returns doc with its managed region replaced by region,
// appending the region when doc has none. Everything outside the markers
// is the operator's text and comes back unchanged.
func splice(doc, region []byte) ([]byte, error) {
	start, end, err := regionBounds(doc)
	if err != nil {
		return nil, err
	}
	if start < 0 {
		if len(bytes.TrimSpace(doc)) == 0 {
			return region, nil
		}
		var out bytes.Buffer
		out.Write(doc)
		if !bytes.HasSuffix(doc, []byte("\n")) {
			out.WriteString("\n")
		}
		out.WriteString("\n")
		out.Write(region)
		return out.Bytes(), nil
	}
	var out bytes.Buffer
	out.Write(doc[:start])
	out.Write(region)
	out.Write(doc[end:])
	return out.Bytes(), nil
}
