package skills

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"

	"github.com/Choaterboater/pika/internal/contract"
	"github.com/Choaterboater/pika/internal/profiles"
	"github.com/Choaterboater/pika/internal/repopath"
)

// The markers delimiting the kernel-owned region of a projection file.
// They are HTML comments so the region is invisible when the file is
// rendered and legible when it is read as text, and they are literal
// rather than templated so a file can be searched for them.
const (
	beginMarker = "<!-- pika:skills:begin -->"
	endMarker   = "<!-- pika:skills:end -->"
)

// origin describes one class of region target: the invocation that
// writes it, and where a change to the text inside its markers actually
// belongs.
//
// The two classes differ in both, and every message derives both from
// here. A file cannot advertise the invocation that did not write it, a
// report cannot send an operator to the form that will not fix their
// file, and a tampered global file is not told to edit a skill directory
// that has nothing to do with it.
type origin struct {
	// command is the invocation, quoted the way every pika message
	// quotes a command.
	command string
	// source is what to do instead of editing the region.
	source string
}

var (
	repoOrigin = origin{
		command: "`pika skills install`",
		source: "make the change in the canonical skill under .agents/skills/" +
			" (or in the profile pack guidance) and regenerate",
	}
	globalOrigin = origin{
		command: "`pika skills install --global`",
		source: "this file is rendered from templates carried inside the pika binary," +
			" so there is nothing local to edit: keep your own words outside the markers," +
			" where they survive every regeneration",
	}
)

// notice is the first line inside every region. It exists for the human
// or agent who opens the file with no idea why it looks generated.
func (o origin) notice() string {
	return "<!-- Generated by " + o.command + ". Everything between these markers is kernel-owned: edit the source, not this copy. -->"
}

// The kinds of input a region is generated from.
const (
	// SourceSkill is a canonical skill file in this repository.
	SourceSkill = "skill"
	// SourceGuidance is one profile pack's agent-guidance.
	SourceGuidance = "guidance"
	// SourceTemplate is a template embedded in this pika binary. It is
	// what the global agent files cite: they are installed outside every
	// repository, so there is no working tree for them to be generated
	// from and the binary is the only source they have.
	SourceTemplate = "template"
)

// Source is one input a projection was generated from, with the digest
// of that input at generation time. Spec §9.2 requires a projection to
// identify its source and digest; this is that identification, and it is
// what makes a stale copy distinguishable from a current one.
type Source struct {
	Kind   string `json:"kind"`
	Ref    string `json:"ref"`
	Digest string `json:"digest"`
}

// sourceLine matches one provenance line inside a region.
var sourceLine = regexp.MustCompile(`^<!-- pika:source (skill|guidance|template) (\S+) (sha256:[0-9a-f]{64}) -->$`)

// body is everything a region renders from: the skill texts that make
// up its prose, and the agent guidance the resolved profile packs
// contribute. Both are inputs with digests, so both appear in the
// provenance header — a projection that changed because go@1's guidance
// changed says so, instead of reporting only that something moved.
//
// The provenance and the rendered region are computed once, at
// construction: every declared projection renders the same bytes, and a
// repository with several of them would otherwise hash and format the
// same inputs once per target.
//
// from is the class of target this region is rendered for. Its notice is
// part of the digested bytes on purpose: the line tells a reader which
// command wrote the file, and a claim inside a kernel-owned region that
// nothing verifies is the exact thing the region digest exists to end.
type body struct {
	skills   []canonical
	guidance []profiles.GuidanceSet
	from     origin
	src      []Source
	region   []byte
	digest   string
}

// newBody composes skills and guidance into the rendered region. skills
// is reordered into readingOrder before anything is computed from it —
// every consumer of a body (Install's write, Inspect's and Verify's
// read-only recompute for comparison) must derive the same bytes from
// the same on-disk skills, so the reorder belongs here once rather
// than at each call site where forgetting it would silently desync a
// write from the verification that is supposed to check it.
func newBody(skills []canonical, guidance []profiles.GuidanceSet, from origin) body {
	b := body{skills: orderForReading(skills), guidance: guidance, from: from}
	b.src = b.provenance()
	core := b.renderCore()
	b.digest = digestOf(core)
	b.region = withRegionDigest(core, b.head(), b.digest)
	return b
}

// head is the fixed opening of this body's rendered region.
func (b body) head() string { return regionHead(b.from.notice()) }

// sources lists the provenance of the rendered region: skills first in
// name order, then guidance in profile-composition order.
func (b body) sources() []Source { return b.src }

// provenance computes that list.
//
// A pack's digest here covers its guidance lines alone, not the whole
// pack. A pack edit that does not touch guidance cannot change what a
// projection says, so it must not be reported as having drifted it;
// profiles.lock is where whole-pack drift is already caught.
func (b body) provenance() []Source {
	out := make([]Source, 0, len(b.skills)+len(b.guidance))
	for _, s := range b.skills {
		out = append(out, Source{Kind: s.kind, Ref: s.rel, Digest: s.digest})
	}
	for _, g := range b.guidance {
		out = append(out, Source{Kind: SourceGuidance, Ref: g.Ref, Digest: digestOf([]byte(strings.Join(g.Lines, "\n")))})
	}
	return out
}

// renderCore builds the kernel-owned region without its own digest
// line: the markers, the provenance header, every canonical skill
// demoted one heading level so it nests under the host document, and
// the stack guidance the profile packs contribute.
//
// These are the exact bytes the region digest covers. Rendering them
// separately is what makes the scheme stable: the digest is a function
// of everything except the line that carries it, so regenerating an
// unchanged projection reproduces the same digest and therefore the
// same file.
func (b body) renderCore() []byte {
	var out bytes.Buffer
	out.WriteString(b.head())
	for _, s := range b.src {
		fmt.Fprintf(&out, "<!-- pika:source %s %s %s -->\n", s.Kind, s.Ref, s.Digest)
	}
	for _, s := range b.skills {
		out.WriteString("\n")
		out.Write(demote(stripFrontmatter(s.body)))
	}
	if len(b.guidance) > 0 {
		out.WriteString("\n## Stack guidance\n\n")
		out.WriteString("From the profile packs this repository selects (")
		for i, g := range b.guidance {
			if i > 0 {
				out.WriteString(", ")
			}
			out.WriteString(g.Ref)
		}
		out.WriteString("):\n\n")
		for _, g := range b.guidance {
			for _, line := range g.Lines {
				fmt.Fprintf(&out, "- %s\n", collapse(line))
			}
		}
	}
	out.WriteString(endMarker + "\n")
	return out.Bytes()
}

// stripFrontmatter removes a leading YAML frontmatter block. The
// frontmatter tells a skill loader when to load a skill; a projection is
// always loaded, so carrying it across would state a condition nothing
// evaluates.
func stripFrontmatter(src []byte) []byte {
	if !bytes.HasPrefix(src, []byte("---\n")) {
		return src
	}
	rest := src[len("---\n"):]
	end := bytes.Index(rest, []byte("\n---\n"))
	if end < 0 {
		return src
	}
	return bytes.TrimLeft(rest[end+len("\n---\n"):], "\n")
}

// frontmatterOf returns the leading YAML frontmatter block of src,
// delimiters included and nothing after them, or nothing when src has
// none. The blank line that separates it from what follows is splice's
// to add, which is why it is not added here: two hands writing the same
// separator produce two of it.
//
// It is the complement of stripFrontmatter, and it exists for one
// target: the omp user-level skill file, whose loader will not surface
// a skill that does not declare `name` and `description` at the very
// top. Frontmatter cannot live inside the kernel-owned region, because
// a region begins with its marker and frontmatter that is not the first
// thing in the file is not frontmatter. So the global skill's own
// template supplies it and it is written above the markers, which keeps
// one text the source of both halves of that file.
func frontmatterOf(src []byte) []byte {
	if !bytes.HasPrefix(src, []byte("---\n")) {
		return nil
	}
	rest := src[len("---\n"):]
	end := bytes.Index(rest, []byte("\n---\n"))
	if end < 0 {
		return nil
	}
	return src[:len("---\n")+end+len("\n---\n")]
}

// demote adds one level to every ATX heading so a skill's own `#` title
// nests beneath the host document's. A heading already at level six is
// left alone: seven hashes is not a heading, and silently emitting one
// would turn a demotion into a deletion.
func demote(src []byte) []byte {
	lines := bytes.Split(src, []byte("\n"))
	for i, line := range lines {
		hashes := 0
		for hashes < len(line) && line[hashes] == '#' {
			hashes++
		}
		if hashes == 0 || hashes >= 6 || hashes >= len(line) || line[hashes] != ' ' {
			continue
		}
		lines[i] = append([]byte("#"), line...)
	}
	return bytes.Join(lines, []byte("\n"))
}

// collapse folds a guidance line onto one line. Pack YAML folds long
// prose across source lines for readability; a Markdown bullet that
// carries those newlines through would end the list item at the first one.
func collapse(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// inspectProjection reports one declared projection against what the
// file on disk holds, without writing anything. The verdict itself is
// inspectRegionFile's; this resolves the contract-declared path and
// refuses one that leaves the repository.
func inspectProjection(root *repopath.Root, p contract.Projection, b body) ProjectionStatus {
	st := ProjectionStatus{Harness: p.Harness, Path: p.Path, Sources: b.sources(), Region: b.digest}
	target, err := insideRoot(root, p.Path)
	if err != nil {
		st.State = StateUnreadable
		st.Detail = err.Error()
		return st
	}
	st.State, st.Detail = inspectRegionFile(target, b)
	return st
}

// staleDetail explains why an intact region no longer matches its
// sources, naming the source that moved when one did. That is what the
// provenance header is for: without it every stale copy reads the same,
// and an operator is told only that something moved.
//
// Reaching here means the region still hashes to the digest it carries,
// so nothing anyone typed is at risk and regenerating is safe. The
// remedy names the invocation that produced this body, because the
// repository form does not fix a global file and the global form does
// not fix a projection.
func staleDetail(region []byte, b body) string {
	cited := parseSources(region)
	had := map[string]Source{}
	var order []string
	for _, s := range cited {
		had[s.Ref] = s
		order = append(order, s.Ref)
	}
	var moved []string
	for _, want := range b.sources() {
		got, ok := had[want.Ref]
		if !ok {
			moved = append(moved, fmt.Sprintf("was generated before %s %s existed", want.Kind, want.Ref))
			continue
		}
		if got.Digest != want.Digest {
			moved = append(moved, fmt.Sprintf("cites %s %s at %s, which is now %s", got.Kind, got.Ref, got.Digest, want.Digest))
		}
	}
	current := map[string]bool{}
	for _, want := range b.sources() {
		current[want.Ref] = true
	}
	for _, ref := range order {
		if !current[ref] {
			moved = append(moved, fmt.Sprintf("cites %s %s, which is no longer one of its sources", had[ref].Kind, ref))
		}
	}
	if len(moved) == 0 {
		// Every source this region cites is where it was, and the
		// region still hashes to its own digest, so nobody edited
		// either side: this pika renders the same inputs differently
		// from the one that wrote the file. Saying "a source moved"
		// here would name a file that did not change.
		return "cites every source at its current digest but no longer matches what this version of pika renders from them; regenerate it with " + b.from.command
	}
	return strings.Join(moved, " and ") + "; regenerate it with " + b.from.command
}

// parseSources reads the provenance lines out of a region.
func parseSources(region []byte) []Source {
	var out []Source
	for _, line := range strings.Split(string(region), "\n") {
		m := sourceLine.FindStringSubmatch(strings.TrimRight(line, "\r"))
		if m == nil {
			continue
		}
		out = append(out, Source{Kind: m[1], Ref: m[2], Digest: m[3]})
	}
	return out
}

// writeProjection regenerates one projection in place and reports the
// result. The rewrite itself is writeRegionFile's; this resolves the
// contract-declared path and refuses one that leaves the repository.
func writeProjection(root *repopath.Root, p contract.Projection, b body) (ProjectionStatus, error) {
	st := ProjectionStatus{Harness: p.Harness, Path: p.Path, Sources: b.sources(), Region: b.digest}
	target, err := insideRoot(root, p.Path)
	if err != nil {
		// Refusing here rather than reporting a state is the point: a
		// path outside the root is not a projection in a bad condition,
		// it is a write this kernel will not perform, and the install
		// that asked for it stops.
		return st, fmt.Errorf("skills: projection %s (harness %s) %w", p.Path, p.Harness, err)
	}
	st.State, st.Detail, st.Written, err = writeRegionFile(target, nil, b)
	return st, err
}
